export default [
  {
    family: "Arial",
    source: "Websafe",
    type: "sans-serif",
    weights: [400, 700],
    italic: "same",
    fallback: ["Helvetica Neue", "Helvetica"],
  },
  { family: "Bitter", source: "Google", type: "serif", weights: [400, 700], italic: [400], fallback: [] },
  { family: "Changa One", source: "Google", type: "sans-serif", weights: [400], italic: "same", fallback: ["Impact"] },
  { family: "Droid Sans", source: "Google", type: "sans-serif", weights: [400, 700], italic: [], fallback: [] },
  { family: "Droid Serif", source: "Google", type: "serif", weights: [400, 700], italic: "same", fallback: [] },
  {
    family: "Exo",
    source: "Google",
    type: "sans-serif",
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    italic: "same",
    fallback: [],
  },
  {
    family: "Georgia",
    source: "Websafe",
    type: "serif",
    weights: [400, 700],
    italic: "same",
    fallback: ["Times", "Times New Roman"],
  },
  { family: "Great Vibes", source: "Google", type: "cursive", weights: [400], italic: [], fallback: [] },
  {
    family: "Impact",
    source: "Websafe",
    type: "sans-serif",
    weights: [700],
    italic: "same",
    fallback: ["Haettenschweiler", "Franklin Gothic Bold", "Charcoal"],
  },
  { family: "Inconsolata", source: "Google", type: "monospace", weights: [400, 700], italic: [], fallback: [] },
  {
    family: "Lato",
    source: "Google",
    type: "sans-serif",
    weights: [100, 300, 400, 700, 900],
    italic: "same",
    fallback: [],
  },
  {
    family: "Merriweather",
    source: "Google",
    type: "serif",
    weights: [300, 400, 700, 900],
    italic: "same",
    fallback: [],
  },
  {
    family: "Montserrat",
    source: "Google",
    type: "sans-serif",
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    italic: "same",
    fallback: [],
  },
  {
    family: "Open Sans",
    source: "Google",
    type: "sans-serif",
    weights: [300, 400, 600, 700, 800],
    italic: "same",
    fallback: [],
  },
  {
    family: "Oswald",
    source: "Google",
    type: "sans-serif",
    weights: [200, 300, 400, 500, 600, 700],
    italic: [],
    fallback: [],
  },
  { family: "PT Sans", source: "Google", type: "sans-serif", weights: [400, 700], italic: "same", fallback: [] },
  { family: "PT Serif", source: "Google", type: "serif", weights: [400, 700], italic: "same", fallback: [] },
  {
    family: "Palatino Linotype",
    source: "Websafe",
    type: "serif",
    weights: [400, 700],
    italic: "same",
    fallback: ["Book Antiqua", "Palatino"],
  },
  {
    family: "Tahoma",
    source: "Websafe",
    type: "sans-serif",
    weights: [400, 700],
    italic: "same",
    fallback: ["Verdana", "Segoe"],
  },
  {
    family: "Times New Roman",
    source: "Websafe",
    type: "serif",
    weights: [400, 700],
    italic: "same",
    fallback: ["TimesNewRoman", "Times", "Baskerville", "Georgia"],
  },
  {
    family: "Trebuchet MS",
    source: "Websafe",
    type: "sans-serif",
    weights: [400, 700],
    italic: "same",
    fallback: ["Lucida Grande", "Lucida Sans Unicode", "Lucida Sans", "Tahoma"],
  },
  {
    family: "Ubuntu",
    source: "Google",
    type: "sans-serif",
    weights: [300, 400, 500, 700],
    italic: "same",
    fallback: ["Helvetica"],
  },
  { family: "Varela", source: "Google", type: "sans-serif", weights: [400], italic: [], fallback: [] },
  { family: "Varela Round", source: "Google", type: "sans-serif", weights: [400], italic: [], fallback: [] },
  {
    family: "Verdana",
    source: "Websafe",
    type: "sans-serif",
    weights: [400, 700],
    italic: "same",
    fallback: ["Geneva"],
  },
  { family: "Vollkorn", source: "Google", type: "serif", weights: [400, 700], italic: "same", fallback: [] },
  {
    family: "system-ui",
    source: "Websafe",
    type: "sans-serif",
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    italic: "same",
    fallback: [
      "-apple-system",
      "BlinkMacSystemFont",
      "Segoe UI",
      "Roboto",
      "Oxygen",
      "Ubuntu",
      "Cantarell",
      "Fira Sans",
      "Droid Sans",
      "Helvetica Neue",
    ],
  },
];
